version: 2.1

jobs:
  build-create-dmg:
    macos:
      xcode: "15.2.0"
    parameters:
      os_version:
        type: string
    steps:
      - checkout
      - run:
          name: List contents of /Applications/
          command: ls -la /Applications/
      - run:
          name: Build Xcode Project
          command: |
            xcodebuild clean build -project Sample.xcodeproj -scheme Sample -configuration Debug -derivedDataPath build -sdk iphonesimulator
      - run:
          name: Install create-dmg
          command: brew install create-dmg
      - run:
          name: Create a disk image using create-dmg
          command: |
            mkdir -p output
            sudo create-dmg \
              --volname "Sample" \
              --window-pos 100 100 \
              --window-size 480 582 \
              --icon-size 128 \
              --icon "Xcode-15.2.app" 240 108 \
              --app-drop-link 240 332 \
              output/Sample_xcode_<<parameters.os_version>>.dmg \
              /Applications/Xcode-15.2.app

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-create-dmg:
          os_version: "macos-14"
      - build-create-dmg:
          os_version: "macos-13"
